
AllCops:
  TargetRubyVersion: 2.7 # adjust for your project
  #EnabledByDefault: true

inherit_gem:
  ted_rubocop_rules: rubocop.yml
# inherit_from: .rubocop_todo.yml # if you have one
inherit_mode:
  merge:
    - Exclude

Style/Documentation:
  Enabled: false
