AllCops:
  TargetRubyVersion: 2.3

# not sure if this is safe quite yet.
Style/FrozenStringLiteralComment:
  Enabled: false

inherit_from:
  - https://raw.githubusercontent.com/tedconf/code-style-guides/master/linters/rubocop/rubocop.yml
