name: Ruby
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7', '3.0']
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    # Setup SSH agent first to allow for checking out repos using SSH, as needed
    #- name: Set up SSH agent
    #  uses: webfactory/ssh-agent@v0.5.3
    #  with:
    #    ssh-private-key: ${{ secrets.TEDCONF_GH_ACTIONS_JENKINS_PRIV_SSH_KEY }}
    - name: Set up Ruby
      # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
      # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      env:
        BUNDLE_RUBYGEMS__TED__COM: ${{ secrets.BUNDLE_RUBYGEMS__TED__COM }}
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run security checks
      run: |
        bundle exec bundle-audit check --update
    - name: Run linters
      run: |
        bundle exec rubocop --parallel
    - name: Run tests
      run: |
        bundle exec rspec
